name: Create GitHub Labels

on:
  workflow_dispatch: # 수동 실행 가능
  push:
    paths:
      - .github/labels.json # labels.json이 변경되었을 때 자동 실행

jobs:
  create-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create labels using GitHub API
        run: |
          LABELS_FILE=".github/labels.json"
          for row in $(jq -c '.[]' "$LABELS_FILE"); do
            name=$(echo "$row" | jq -r '.name')
            color=$(echo "$row" | jq -r '.color')
            description=$(echo "$row" | jq -r '.description')

            curl -s -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/labels \
              -d "{\"name\":\"$name\", \"color\":\"$color\", \"description\":\"$description\"}" \
              | jq '.name' || echo "Failed to create $name"
          done
